//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCatsBot.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cats_viewed_by_users
    {
        public int id { get; set; }
        public long user_id { get; set; }
        public int cat_id { get; set; }
        public string file_id { get; set; }
        public System.DateTime datetime_viewed { get; set; }
        public bool viewed { get; set; }
        public bool liked { get; set; }
        public bool disliked { get; set; }
    }
}
