//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCatsBot.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public long user_id { get; set; }
        public string user_name_fix { get; set; }
        public System.DateTime datetime_user_registered { get; set; }
        public string user_lang_var { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public long chat_id { get; set; }
    }
}
