//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCatsBot.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
     internal partial class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FCatsBot.Strings.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author: Ivan Koroteev. Using C# and PostgreSql and Google Cloud Vision neural networks..
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is bigger than 20 MB!.
        /// </summary>
        internal static string BigFile {
            get {
                return ResourceManager.GetString("BigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Donate $.
        /// </summary>
        internal static string btnDonate {
            get {
                return ResourceManager.GetString("btnDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        internal static string btnHelp {
            get {
                return ResourceManager.GetString("btnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add more cats.
        /// </summary>
        internal static string btnMore {
            get {
                return ResourceManager.GetString("btnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rate cats pics.
        /// </summary>
        internal static string btnVote {
            get {
                return ResourceManager.GetString("btnVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry, this urls is not processed. Send cat picture separately..
        /// </summary>
        internal static string CannotProcessUrl {
            get {
                return ResourceManager.GetString("CannotProcessUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cat №{0}.
        /// </summary>
        internal static string CatCaption {
            get {
                return ResourceManager.GetString("CatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cat from thecatapi.com.
        /// </summary>
        internal static string CatFromApi {
            get {
                return ResourceManager.GetString("CatFromApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cat from your url.
        /// </summary>
        internal static string CatFromUrl {
            get {
                return ResourceManager.GetString("CatFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok, my commands are.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry, can not process ContactMessage.
        /// </summary>
        internal static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not recognized. .
        /// </summary>
        internal static string Echo {
            get {
                return ResourceManager.GetString("Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while processing your {0}.
        /// </summary>
        internal static string ErrorFile {
            get {
                return ResourceManager.GetString("ErrorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type /help for list of commands and language change..
        /// </summary>
        internal static string GetHelp {
            get {
                return ResourceManager.GetString("GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на inline cat.
        /// </summary>
        internal static string InlineText {
            get {
                return ResourceManager.GetString("InlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0}  and choose picture with cat in menu Gallery/Camera (Photo on desktop), up to 5 MB, and it will be sent to moderation using Google Cloud Vision.
        ///Or you can use /catapi command to send random cat from thecatapi.com to moderation.
        ///Also you can send to bot url to cat picture..
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language set..
        /// </summary>
        internal static string LangChanged {
            get {
                return ResourceManager.GetString("LangChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на fa3ew.
        /// </summary>
        internal static string LangSelect {
            get {
                return ResourceManager.GetString("LangSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your location is Lat={0} Long={1}.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на photo sent to manual moderation (limit of 250 pics per day reached).
        /// </summary>
        internal static string ModManual {
            get {
                return ResourceManager.GetString("ModManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No cats found. Seems like you viewed every cat!.
        /// </summary>
        internal static string NoCatsFound {
            get {
                return ResourceManager.GetString("NoCatsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no urls for you, sorry..
        /// </summary>
        internal static string NoUrls {
            get {
                return ResourceManager.GetString("NoUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate bot at https://telegram.me/storebot?start=fcatsbot.
        /// </summary>
        internal static string RateBot {
            get {
                return ResourceManager.GetString("RateBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на you are registered user.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на photo sent to moderation using Google Cloud Vision.
        /// </summary>
        internal static string SavedOnMega {
            get {
                return ResourceManager.GetString("SavedOnMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на photo saved .
        /// </summary>
        internal static string SavedPhoto {
            get {
                return ResourceManager.GetString("SavedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Special thanks to:.
        /// </summary>
        internal static string SpecialThanks {
            get {
                return ResourceManager.GetString("SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok, bot started. 
        ///MAIN BOT COMMANDS: 
        ////vote - Vote for cats in our base!
        ////catapi - add more cats to our base from thecatapi.com 
        ///
        ///Send me your pictures with cats!.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry, type {0} not supported..
        /// </summary>
        internal static string TypeNotSupported {
            get {
                return ResourceManager.GetString("TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only urls with jpg or png files are accepted!.
        /// </summary>
        internal static string UrlNoJpg {
            get {
                return ResourceManager.GetString("UrlNoJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Views: {0}.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You already voted for this cat.
        /// </summary>
        internal static string VoteFalse {
            get {
                return ResourceManager.GetString("VoteFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue voting - press.
        /// </summary>
        internal static string VoteMore {
            get {
                return ResourceManager.GetString("VoteMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на nothing. Send another picture..
        /// </summary>
        internal static string WatsonEmpty {
            get {
                return ResourceManager.GetString("WatsonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google Cloud Vision say there is cat on this picture! Moderation was successful. Here what was found:.
        /// </summary>
        internal static string WatsonHasCat {
            get {
                return ResourceManager.GetString("WatsonHasCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google Cloud Vision say there is NO cat on this picture! It will go to manual moderation. Here what was found:.
        /// </summary>
        internal static string WatsonNoCat {
            get {
                return ResourceManager.GetString("WatsonNoCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google Cloud Vision say this is {0} with {1} score.
        /// </summary>
        internal static string WatsonSay {
            get {
                return ResourceManager.GetString("WatsonSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Everyone likes cats!.
        /// </summary>
        internal static string WhyMega {
            get {
                return ResourceManager.GetString("WhyMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have {0} urls.
        /// </summary>
        internal static string YouHaveUrls {
            get {
                return ResourceManager.GetString("YouHaveUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random Cat:.
        /// </summary>
        internal static string YourLatestUrl {
            get {
                return ResourceManager.GetString("YourLatestUrl", resourceCulture);
            }
        }
    }
}
